# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 255706d9d23104e063f324ef534c77999ba3e5aea5f171502b177873fc243272edef2c2ba7109522be193a9761d576a681cde930e36469b37d6e31780a5b3f26

test:
  secret_key_base: 54b17ed6491ab3554ff139258f2bee3eb4a063ae7c7a525b951cab9dcf6b0ac935edd5d6eba47c35e682b9597c2284d7ea469e74a1d989cb577937f60ef66a1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
